/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance.restaurant;

import inheritance.restaurant.review.Review;

import java.util.ArrayList;

public class Restaurant {
    public String name;
    //TODO: refactor starTier to float/double to better handle review score mean?
    public int starTier;
    public int priceTier;

    public Restaurant(String name, int starTier, int priceTier) {
        this.name = name;
        this.starTier = starTier;
        this.priceTier = priceTier;
    }

    @Override
    public String toString() {
        String restaurantString = this.name + " is a " + this.starTier + "-star restaurant in the " + this.priceTier + "-out-of-5 price tier.";
        return restaurantString;
    }

    public ArrayList<Review> reviewList = new ArrayList<>();


    public void addReview(Review reviewToAdd) {
        int starSum = 0;

        if (!reviewList.contains(reviewToAdd)) {
            reviewList.add(reviewToAdd);
            for (Review previousReview : reviewList) {
                starSum = starSum + previousReview.reviewStars;
            }
            // TODO: Refactor starTier average with non-integer division?
            this.starTier = starSum / reviewList.toArray().length;
        } else {
            System.out.println("Review already registered.");
        }
    }
}
