/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import inheritance.review.Review;

import java.util.ArrayList;

public class Restaurant implements AddReviewable{
    public String name;
    //TODO: refactor starTier to float/double to better handle review score mean?
    public int starTier;
    public int priceTier;
    public String description;

    public Restaurant(String name, String description, int starTier, int priceTier) {
        this.name = name;
        this.starTier = starTier;
        this.priceTier = priceTier;
        this.description = description;
    }

    @Override
    public String toString() {
        String restaurantString = this.name + " is a " + this.starTier + "-star restaurant in the " + this.priceTier + "-out-of-5 price tier.";
        return restaurantString;
    }

    public ArrayList<Review> reviewList = new ArrayList<>();


    public void addReview(String reviewer, int reviewStars, String optionalMovieName) {
        int starSum = 0;
        Review reviewToAdd = new Review(this, reviewer, reviewStars, optionalMovieName);
        if (!reviewList.contains(reviewToAdd))
            reviewList.add(reviewToAdd);
        for (Review previousReview : reviewList) {
            starSum = starSum + previousReview.reviewStars;
        }
        // TODO: Refactor starTier average with non-integer division?
        this.starTier = starSum / reviewList.toArray().length;
    }
}
