/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import inheritance.review.Review;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

class LibraryTest {


    @Test
    public void RestaurantConstructorTest () {
        Restaurant sampleTown = new Restaurant("Sample Town", 3, 2);
        assertEquals(3, sampleTown.starTier, "Expected starTier from input did not equal constructed restaurant's starTier value.");
    }

    @Test
    public void ReviewConstructorTest () {
        Restaurant sampleTown = new Restaurant("Sample Town", 3, 2);
        Review testReview = new Review(sampleTown, "Tim", 5);
        assertEquals(5, testReview.reviewStars, "Expected reviewStars from input did not equal constructed review's reviewStars value.");
    }

    @Test
    public void toStringMethodTests () {
    Restaurant testys = new Restaurant ("Testy's", 3, 4);

    Review harsh = new Review (testys, "G. Harshly", 2);

        System.out.println(testys);
        System.out.println(harsh);
    }

    @Test
    public void addReviewTest () {
        Restaurant sampleTown = new Restaurant("Sample Town", 3, 2);
        Review testReview = new Review(sampleTown, "Tim", 5);
        sampleTown.addReview(testReview);
        // TODO: Write assertion for addReview method test
        System.out.println(sampleTown.reviewList);
    }

    @Test void addReviewStarAveragingTest () {
        Restaurant sampleTown = new Restaurant("Sample Town", 3, 2);
        Review testReview = new Review(sampleTown, "Tim", 5);
        Review harsh = new Review (sampleTown, "G. Harshly", 2);
        Review brutal = new Review (sampleTown, "Bittman", 0);

        sampleTown.addReview(testReview);
        sampleTown.addReview(harsh);
        sampleTown.addReview(brutal);

        System.out.println("Sample Town's updated starTier from review average is: " + sampleTown.starTier);
        assertEquals(2, sampleTown.starTier, "starTier did not update to equal mean of added reviewStars");
    }
    //TODO: refactor tests
    @Test void addMovieTest () {

    }

    @Test void removeMovieTest () {

    }

    @Test void addReviewForShopTest () {

    }

    @Test void addReviewForTheaterWithMovieTest () {

    }

    @Test void toStringTheaterTest () {

    }
}
